# serverless.yml

service: serverless-flask-test6

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
#  region: cn-north-1
  region: us-east-1
  endpointType: regional


package:
  exclude:
      - .DS_Store
      - __pycache__/
      - .dist-info/

# resources:
#   Resources:
#     AppLambdaPermissionApiGateway:
#       Properties:
#         Principal: 'apigateway.amazonaws.com.cn'

#resources:
#  Resources:
#    AppLambdaPermissionApiGateway:
#      Properties:
#        Principal: apigateway.amazonaws.com
#          Fn::Join:
#            - ''
#            - - apigateway.
#              - {Ref: 'AWS::URLSuffix'}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'